name: Test Nxtstart Creation 👷
on:
  push:
  schedule:
    - cron: 0 9 * * 1
jobs: 
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Setup Node.js 🔧
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      # needed to avoid npm authentication problems in github action runner when trying to npm install
      - run: rm package-lock.json
      - run: npm install
      # install create-nxtstart-app
      - run: npm install -g
      # run test
      - run: npm run testNpm
  yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Setup Node.js 🔧
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      # needed to avoid npm authentication problems in github action runner when trying to npm install
      - run: rm package-lock.json
      - run: npm install
      # install create-nxtstart-app
      - run: npm install -g
      # run test
      - run: npm run testYarn